author: "Sander Laarhoven"
copyright: "Copyright (c) Nog Nooit Meegemaakt 2016"
version: "1.0.0"
title: "Nog Nooit Meegemaakt"
logo: "/assets/img/logo.png"
domain: "https://nognooitmeegemaakt.nl"
collections:
  groups:
    output: true
    permalink: /groep/:path/
