author: "Sander Laarhoven"
owner: "Stichting Scouting Groep Petrus en Paulus"
copyright: "Copyright (c) Nog Nooit Meegemaakt 2018"
version: "1.0.0"
title: "Nog Nooit Meegemaakt"
domain: "https://nognooitmeegemaakt.nl"
logo: "https://nognooitmeegemaakt.nl/assets/img/logo.png"
description: "Scoutinggroep P&P verzorgt activiteiten die jij nog nooit hebt meegemaakt! Lijkt het je leuk om mee te doen? Kom dan een keer kijken, of meld je aan!"
keywords: "scouting, den bosch, P&P, petrus en paulus, nog nooit meegemaakt, outdoor, stoer"
collections:
  groups:
    output: true
    permalink: /groep/:path/
  agenda:
    output: true
    permalink: /programma/:path/
markdown: kramdown
jaarplanning: "/assets/docs/jaarplanning-2018-2019.pdf"
