##
## nognooitmeegemaakt.nl
##

owner: "Stichting Scouting Groep Petrus en Paulus"
copyright: "Copyright (c) Nog Nooit Meegemaakt 1934-2018"
version: 3.0.0

title: "Nog Nooit Meegemaakt"
description: "Scoutinggroep P&P verzorgt activiteiten die jij nog nooit hebt meegemaakt! Lijkt het je leuk om mee te doen? Kom dan een keer kijken, of meld je aan!"
keywords: "scouting, den bosch, P&P, petrus en paulus, nog nooit meegemaakt, outdoor, stoer"

logo: "/assets/img/logo.png"

jaarplanning: "/assets/docs/jaarplanning-2017-2018.pdf"

collections:
  pages:
    output: true
  groups:
    output: true
    permalink: /groep/:path/
  agenda:
    output: true
    permalink: /programma/:path/
markdown: kramdown
